export interface Onboardee{
    id : Number,
    name : String,
    email: String ,
    dob : Date,
    contactno : String,
    address : String,
    demandID : Number,
    location : String ,
    skills : String,
    eta : Date,
    bgc_status : String,
    onboarding_status : String,
    onboarding_date : Date,
    ms_hiring_manager : String,
    creationTm : Date,
    lastmodifiedTm : Date,
    designation : String,
    experience : String ,
    graduation : String,  
}